# Generated by Django 4.2.1 on 2025-06-27 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('alias', models.CharField(default='default', max_length=100)),
                ('date', models.DateField()),
                ('content_id', models.CharField(blank=True, max_length=100, null=True)),
                ('content_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_unit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_unit_name', models.CharField(blank=True, max_length=200, null=True)),
                ('earnings', models.FloatField(default=0.0)),
                ('earnings_usd', models.FloatField(default=0.0)),
                ('impressions', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('ppc', models.FloatField(default=0.0)),
                ('order_count', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(verbose_name='적용년월')),
                ('usd_to_krw', models.DecimalField(decimal_places=2, help_text='1 USD = ? KRW', max_digits=10, verbose_name='USD/KRW 환율')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '환율',
                'verbose_name_plural': '환율',
                'db_table': 'exchange_rate',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('uname', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.SmallIntegerField(default=1)),
                ('request_key', models.CharField(blank=True, db_column='requestKey', max_length=8, null=True, unique=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='PurchaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('company_name', models.CharField(max_length=100, verbose_name='거래처명')),
                ('service_name', models.CharField(max_length=100, verbose_name='서비스명')),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='기본 단가')),
                ('default_unit_type', models.CharField(choices=[('percent', '퍼센트 (%)'), ('rate', '요율')], default='percent', max_length=10, verbose_name='기본 단가 유형')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_important', models.BooleanField(default=False, verbose_name='주요 퍼블리셔')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_groups', to='stats.member')),
                ('user', models.ForeignKey(help_text='설정 소유 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '매입 그룹',
                'verbose_name_plural': '매입 그룹',
                'db_table': 'purchase_group',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('main', '메인 계정'), ('sub', '서브 계정')], default='main', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_fetch_days', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField()),
                ('request_key', models.CharField(db_column='requestKey', max_length=8)),
                ('visit_count', models.BigIntegerField(db_column='visitCount', default=0, help_text='페이지뷰')),
                ('powerlink_count', models.BigIntegerField(db_column='powerlinkCount', default=0, help_text='파워링크 클릭')),
            ],
            options={
                'verbose_name': '전체 통계',
                'verbose_name_plural': '전체 통계',
                'db_table': 'tbTotalStat',
                'unique_together': {('sdate', 'request_key')},
            },
        ),
        migrations.CreateModel(
            name='SettlementDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='정산주관부서명', max_length=100)),
                ('user', models.ForeignKey(help_text='설정 소유 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '정산주관부서',
                'verbose_name_plural': '정산주관부서',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(help_text='그룹 고유 코드', max_length=100, unique=True)),
                ('group_name', models.CharField(help_text='그룹명', max_length=200)),
                ('company_name', models.CharField(help_text='업체명', max_length=100)),
                ('service_name', models.CharField(help_text='서비스명', max_length=100)),
                ('issue_type', models.CharField(choices=[('정발행', '정발행'), ('역발행', '역발행'), ('영세율', '영세율')], default='정발행', help_text='발행유형', max_length=50)),
                ('settlement_timing', models.CharField(blank=True, help_text='정산시기', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('settlement_department', models.ForeignKey(blank=True, help_text='정산주관부서', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.settlementdepartment')),
                ('user', models.ForeignKey(blank=True, help_text='데이터 소유 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.CharField(max_length=50, verbose_name='퍼블리셔 코드')),
                ('year_month', models.DateField(verbose_name='적용년월')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='단가')),
                ('unit_type', models.CharField(choices=[('percent', '퍼센트 (%)'), ('rate', '요율')], default='percent', max_length=10, verbose_name='단가 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(help_text='설정 소유 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '매입 단가',
                'verbose_name_plural': '매입 단가',
                'db_table': 'purchase_price',
            },
        ),
        migrations.CreateModel(
            name='PurchaseGroupAdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('adsense', '구글 애드센스'), ('admanager', '구글 애드매니저')], max_length=20, verbose_name='플랫폼')),
                ('ad_unit_id', models.CharField(max_length=100, verbose_name='광고 단위 ID')),
                ('ad_unit_name', models.CharField(blank=True, max_length=200, verbose_name='광고 단위명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('purchase_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_units', to='stats.purchasegroup', verbose_name='퍼블리셔 그룹')),
            ],
            options={
                'verbose_name': '퍼블리셔 그룹 광고 단위',
                'verbose_name_plural': '퍼블리셔 그룹 광고 단위',
                'db_table': 'purchase_group_ad_unit',
            },
        ),
        migrations.CreateModel(
            name='PlatformCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('encrypted_client_id', models.BinaryField(blank=True, null=True)),
                ('encrypted_secret', models.BinaryField(blank=True, null=True)),
                ('encrypted_email', models.BinaryField(blank=True, null=True)),
                ('encrypted_password', models.BinaryField(blank=True, null=True)),
                ('token', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('login_pw', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('report_resource_name', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('report_id', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('network_code', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='수익 날짜')),
                ('section', models.CharField(choices=[('publisher', '퍼블리셔'), ('partners', '파트너스'), ('stamply', '스탬플리'), ('publisher_cost', '퍼블리셔 매입비용'), ('partners_cost', '파트너스 매입비용'), ('stamply_cost', '스탬플리 매입비용')], help_text='수익 구분 (퍼블리셔, 파트너스, 스탬플리, 매입비용)', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='기타 수익 금액', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='데이터 소유 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일별 기타수익',
                'verbose_name_plural': '일별 기타수익',
                'ordering': ['-date', 'section'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True, help_text='거래일 (엑셀: 작성시기)')),
                ('year_month', models.DateField(db_index=True, editable=False, help_text='매출 년월 (매월 1일로 저장)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='금액 (엑셀: 품목단가)', max_digits=15)),
                ('service_code', models.CharField(db_index=True, default='', help_text='서비스 고유 코드 (승인번호)', max_length=100)),
                ('company_name', models.CharField(default='', help_text='업체명 (엑셀: 상호)', max_length=100)),
                ('service_name', models.CharField(default='', help_text='서비스명 (엑셀: 품목명)', max_length=100)),
                ('group', models.ForeignKey(blank=True, help_text='서비스 그룹 (자동 매칭)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.servicegroup')),
                ('user', models.ForeignKey(blank=True, help_text='데이터 소유 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(help_text='조정 대상 년월 (매월 1일로 저장)')),
                ('adjustment_type', models.CharField(choices=[('sales', '매출 조정'), ('purchase', '매입 조정')], help_text='조정 유형', max_length=20)),
                ('sales_type', models.CharField(help_text='매출/매입 구분 (예: 퍼블리셔, 파트너스)', max_length=100)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, help_text='조정 금액', max_digits=15)),
                ('adjustment_note', models.TextField(blank=True, help_text='조정 내역')),
                ('tax_deadline', models.DateField(blank=True, help_text='세금계산서 수취기한 (매입 조정시만 사용)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='데이터 소유 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '월별 매출/매입 조정',
                'verbose_name_plural': '월별 매출/매입 조정',
                'ordering': ['-year_month', 'adjustment_type', 'sales_type'],
            },
        ),
        migrations.CreateModel(
            name='MemberStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.CharField(help_text='일자', max_length=8)),
                ('request_key', models.CharField(db_column='requestKey', help_text='cp 코드', max_length=8)),
                ('click_cnt', models.IntegerField(db_column='clickCnt', default=0, help_text='유효 페이지뷰')),
                ('point', models.FloatField(default=0, help_text='파트너스 포인트')),
            ],
            options={
                'verbose_name': '제휴사 통계',
                'verbose_name_plural': '제휴사 통계',
                'db_table': 'tbMemberStat',
                'unique_together': {('sdate', 'request_key')},
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['request_key'], name='member_request_5636c6_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['uid'], name='member_uid_3c357a_idx'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='user',
            field=models.ForeignKey(help_text='설정 소유 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adstats',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adstats', to='stats.platformcredential'),
        ),
        migrations.AddField(
            model_name='adstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='settlementdepartment',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseprice',
            unique_together={('user', 'request_key', 'year_month')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasegroupadunit',
            unique_together={('purchase_group', 'platform', 'ad_unit_id')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasegroup',
            unique_together={('user', 'member', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='platformcredential',
            unique_together={('user', 'platform', 'alias')},
        ),
        migrations.AlterUniqueTogether(
            name='otherrevenue',
            unique_together={('user', 'date', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlysales',
            unique_together={('service_code', 'year_month')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyadjustment',
            unique_together={('user', 'year_month', 'adjustment_type', 'sales_type')},
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('user', 'year_month')},
        ),
        migrations.AlterUniqueTogether(
            name='adstats',
            unique_together={('user', 'platform', 'alias', 'date', 'content_id', 'ad_unit_id')},
        ),
    ]
