# Generated by Django 4.2.1 on 2025-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysales',
            name='business_number',
            field=models.CharField(blank=True, default='', help_text='사업자번호 (XXX-XX-XXXXX)', max_length=12),
        ),
        migrations.AddIndex(
            model_name='adstats',
            index=models.Index(fields=['user', 'date'], name='stats_adsta_user_id_e91076_idx'),
        ),
        migrations.AddIndex(
            model_name='adstats',
            index=models.Index(fields=['user', 'platform', 'date'], name='stats_adsta_user_id_a4259c_idx'),
        ),
        migrations.AddIndex(
            model_name='adstats',
            index=models.Index(fields=['user', 'ad_unit_id', 'date'], name='stats_adsta_user_id_368130_idx'),
        ),
        migrations.AddIndex(
            model_name='adstats',
            index=models.Index(fields=['user', 'platform', 'ad_unit_id', 'date'], name='stats_adsta_user_id_267f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='adstats',
            index=models.Index(fields=['date', 'platform'], name='stats_adsta_date_11cde5_idx'),
        ),
        migrations.AddIndex(
            model_name='adstats',
            index=models.Index(fields=['ad_unit_id', 'platform'], name='stats_adsta_ad_unit_5c7ad1_idx'),
        ),
    ]
