# Generated by Django 4.2.1 on 2025-07-14 01:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0002_monthlysales_business_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlysales',
            unique_together={('user', 'service_code', 'year_month')},
        ),
    ]
