# Generated by Django 4.2.1 on 2025-07-29 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0003_alter_monthlysales_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='memberstat',
            options={'managed': False, 'verbose_name': '제휴사 통계', 'verbose_name_plural': '제휴사 통계'},
        ),
        migrations.AlterModelOptions(
            name='totalstat',
            options={'managed': False, 'verbose_name': '전체 통계', 'verbose_name_plural': '전체 통계'},
        ),
        migrations.AlterUniqueTogether(
            name='purchasegroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchasegroup',
            name='member_request_key',
            field=models.CharField(db_column='member_request_key', default='', max_length=8, verbose_name='퍼블리셔 코드'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasegroup',
            unique_together={('user', 'member_request_key', 'is_active')},
        ),
        migrations.RemoveField(
            model_name='purchasegroup',
            name='member',
        ),
    ]
